version: '2'
services:
    swoft-dev:
        container_name: swoft
        image: swoft/swoft:latest
        ports: # 端口映射: 本地端口 -> 容器内端口
            - "9050:80"
        volumes: # 文件挂载: 本地文件路径 -> 容器内文件路径
            - /home/gzh/swoft:/var/www/swoft
        stdin_open: true
        tty: true
        command: /bin/bash