version: '3'

services:
    swoft:
       image: swoft/swoft:latest
#       build: ./
       ports:
         - "6788:80"
       volumes:
         - ./:/var/www/swoft
       stdin_open: true 
       tty: true
       privileged: true
       entrypoint: ["php", "/var/www/swoft/bin/swoft", "ws:start"]

       
container_name: mySwoft
